IncrementalDOM.elementOpen('div', null, null, 'class', 'test');
IncrementalDOM.text(data.name);
IncrementalDOM.elementClose('div');
IncrementalDOM.text('\n');
IncrementalDOM.elementOpen('div', null, null, 'class', data.class);
IncrementalDOM.text(data.name);
IncrementalDOM.elementClose('div');
IncrementalDOM.text('\n');
IncrementalDOM.elementOpen('player-list', null, null, 'class', 'test');
IncrementalDOM.text(data.name);
IncrementalDOM.elementClose('player-list');
IncrementalDOM.text('\n');
IncrementalDOM.elementOpen('div', null, null, 'class', 'hi');
IncrementalDOM.skip();
IncrementalDOM.elementClose('div');
IncrementalDOM.text('\n');
IncrementalDOM.elementOpen('player-list', null, null, 'class', 'hi');
IncrementalDOM.skip();
IncrementalDOM.elementClose('player-list');
IncrementalDOM.text('\n');
